google/oauth2l

oauth2l/__init__.py, oauth2l/oauth2l_test.py, setup.py, tox.ini
1. Remove the bogus log messages generated by the old multistore_file module by switching to multiprocess_file_storage module.
2. Add cache for getting 2LO token by using the same multiprocess_file_storage module.
=> Remove bogus log messages and add cache for 2LO

oauth2l/__init__.py, oauth2l/oauth2l_test.py
The reset command removes the local credential cache file.
Example usage:
$ oauth2l reset
=> Add reset command

oauth2l/__init__.py
For both service account secret and client secret, there are URIs such as token_uri, auth_uri in the token. We should use whatever provided in the token instead of default to production oauth2 addresses.
=> Use URIs in provided json instead of default one.

oauth2l/__init__.py
This patch reuses an existing variable (`_SCOPE_PREFIX`) to set the authentication scopes (`_GCLOUD_SCOPES`).
=> use _SCOPE_PREFIX to define _GCLOUD_SCOPES

go/src/oauth2client/oauth2client.go, go/src/oauth2client/token.go, go/src/oauth2l/main.go
Tests pending
To try it:
export GOPATH=[path/to]/oauth2l/oauth2l-go
go run [path/to]/oauth2l-go/src/oauth2l/oauth2l.go --json <secret.json> fetch cloud-platform
=> Add oauth2l-go

go/src/oauth2client/oauth2client.go, go/src/oauth2client/token.go
=> Add expiry to token in preparation for cache.

.coveragerc, .gitignore, MANIFEST.in, oauth2l/__init__.py, oauth2l/oauth2l_test.py, setup.cfg, setup.py, tox.ini
* Setuptools is available in every modern python environment, no need to fall back to ez_setup (which is abandoned).
* Use io.open instead of open.
* Remove tests_requires, as it doesn't do anything.
* Use pytest instead of the unmaintained nosetests.
* Use coveragerc instead of arguments to the test function.
* Add setup.cfg to allow distribution as a universal wheel.
* Single-source the version number using pkg_resources.
* Fix broken tests.
* Fix manifest to properly include test resources.
=> Fix packaging and test setup.

go/sgauth/default.go, go/sgauth/grpc.go, go/sgauth/http.go, go/sgauth/internal/const.go, go/sgauth/internal/grpc.go, go/sgauth/internal/http.go, go/sgauth/internal/token.go, go/sgauth/settings.go
- Attach fields into headers in both HTTP and gRPC
- Refactor the gRPC token source code for better readability
- Move HTTP transport code into internal/http.go
=> Support QuotaUser/Project and IAMAuthToken

go/sgauth/README.md, go/sgauth/credentials/file.go
* 2LO flow is not working with ~/.config/gcloud/application_default_credentials.json as it doenst contain fields token_uri & auth_uri
* So pointing them to default URLs
=> Added default auth & token URLs instead from the wellknownfile

README.md, sgauth/settings.go
Update README since `go` directory no longer exists.
Reintroduce `IAMAuthToken string` since it is still referenced by some code.
=> Fix Installation

util/cache.go, util/tasks.go
- Also change the token cache file name to avoid conflicting with the Python version.
=> Skip print and cache if the token fetch failed

sgauth/internal/token_retriever.go
test-www.sandbox.googleapis.com server does not implement the OAuth 2.0 spec fully so we need to add it into the whitelist for special handling.
For more details please read https://code.google.com/p/goauth2/issues/detail?id=31
=> Add test-www.sandbox.googleapis.com into whitelist

sgauth/appengine_hook.go
'go vet' detects the error in the existing version
./appengine_hook.go:15: +build comment must appear before package clause
and be followed by a blank line
Without this fix, this hook is pulled in for all builds, and causes the tool to behave as if it's running on AppEngine all the time.
=> Fix build tag

sgauth/default.go, util/cache.go
This allows redirecting the location of the cache file via the `HOME` environment variable. Without this, the location cannot be changed by users. I'm not sure sgauth/default.go is still the preferred location for `GuessUnixHomeDir`, but I didn't want to introduce too many changes.
=> use GuessUnixHomeDir in cacheLocation

main.go, util/cache.go
This change adds a new flag, --cache, that controls the cache file location and allows disabling caching.
This is useful when oauth2l is used in automated scripts, where caching can add unpredicability to the results, while at the same time allowing more fine-grained control than just "oauth2l reset".
This change also improves the help message by printing the defined flags descriptions and defaults directly from the flag.FlagSet.
=> Allow greater control over caching

README.md, main.go, util/curl.go, util/sso.go, util/tasks.go
-Enhanced command-line flag parsing via "go-flags" library. This improves code readability and provides context-aware help messages. Also provides enforcement of required flags, and rejects incompatible flags.
-Added explicit flags for GUAC arguments such as "scope" and "audience". Maintains backward compatibility with implicit flags and deprecated flags.
-Added support for a new "curl" command, which is a short-cut for making a curl request with a fetched token.
-Updated documentation.
=> Improved OAuth2l Client Interface

.travis.yml
Also stops running Python integration tests.
=> Update Travis to run Go integration tests.

README.md, integration/cli_test.go, main.go, util/tasks.go
The documentation mentions that "oauth2l test" returns 0 or 1, but the
current code prints the value instead of setting an exit code. This is
not useful for scripting.
This commit still keeps the printing part for backwards-compatibility
reasons.
=> Use exit code in addition of print for "test"

README.md, integration/cli_test.go, integration/fixtures/fake-client-secrets-expired-token.json, integration/fixtures/mock-expired-token-response.json, main.go, util/refresh.go, util/tasks.go
1. Do not return expired access tokens from the cache to the user.
2. Automatically refresh expired access token via refresh token, if "refresh" option is enabled.
=> Improve handling of expired access tokens in cache

Makefile
Update dev rule from Makefile by removing the deprecated -i flag from the go install command.
=> Remove deprecated -i flag

integration/cli_test.go, integration/fixtures/fake-client-secrets-3lo-loopback.json, integration/fixtures/fake-client-secrets-expired-token-3lo-loopback.json, integration/fixtures/fake-client-secrets-expired-token.json, integration/fixtures/fake-client-secrets.json, integration/golden/curl-3lo-loopback.golden, integration/golden/fetch-3lo-loopback-refresh-token.golden, integration/golden/fetch-3lo-loopback-userinfo.golden, integration/golden/fetch-3lo-loopback.golden, integration/golden/header-3lo-loopback.golden, util/cache.go, util/loopback.go
Hi Andy,
3LO loopback testing is complete - all tests are passing!
FYI: 
I found some bugs in the cache that were a little difficult to debug. In summary, the cache key was not working. Mainly because the regex exp did not take into account new lines. The credentials file provided in the tests consisted of multiple lines. In contrast, the file provided by GCP had a single line. (see further notes below)
TODO:
I tried to split the test file into multiple, but there are many technicalities that kept me from it. I think that should be a task of its own and did not want to make it part of this commit. 
Please let me know if you have any further questions. As always, I tried to make the code as readable as possible!
Thanks for reviewing,
Ulises
=> Enabled 3LO loopback tests

integration/cli_test.go, util/curl.go
=> Inherit OS stdio in curl command

Makefile
requires double "$" when referencing temp variables.
=> chore: Update Makefile to support arm64 for darwin and linux (syntax fix 2)
